-- Пользователи
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    birthday DATE NOT NULL
    );

-- Рейтинги MPA
CREATE TABLE IF NOT EXISTS mpa_rating (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name VARCHAR(10) NOT NULL UNIQUE
    );

-- Жанры
CREATE TABLE IF NOT EXISTS genre (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL UNIQUE
    );

-- Фильмы
CREATE TABLE IF NOT EXISTS films (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL CHECK (duration > 0),
    rating_id BIGINT NOT NULL,
    FOREIGN KEY (rating_id) REFERENCES mpa_rating(id)
    );

-- Связь фильм-жанр
CREATE TABLE IF NOT EXISTS film_genre (
                                          film_id BIGINT NOT NULL,
                                          genre_id BIGINT NOT NULL,
                                          PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genre(id) ON DELETE CASCADE
    );

-- Лайки фильмов
CREATE TABLE IF NOT EXISTS film_likes (
                                          film_id BIGINT NOT NULL,
                                          user_id BIGINT NOT NULL,
                                          PRIMARY KEY (film_id, user_id),
    FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );

-- Дружба
CREATE TABLE IF NOT EXISTS friendship (
                                          user_id BIGINT NOT NULL,
                                          friend_id BIGINT NOT NULL,
                                          status BOOLEAN DEFAULT FALSE,
                                          PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (friend_id) REFERENCES users(id) ON DELETE CASCADE
    );
